added some comments to classes and methods
hey-world-team/currency_converter_cb_ru pull request #14
Opened 2023-06-28 17:27 UTC by rassl95

2023-07-03 20:05 UTC, dmitr2ish requested changes
Need changes:
- do have not need to push your properties and commented properties;
- a lot of not completed java doc comments, try to describe what to do this method or class, also don't forget describe  arguments, exceptions and a return value;
- wrong naming of history service and history repository and name of saving history method;
- code style issues;
- For all new logic need to add unit tests:
 - history repository
 - history service

2023-07-03 20:05 UTC, dmitr2ish commented on src/main/java/com/github/hey_world_team/currency_converter/service/FileService.java
> +     * @param path
not completed comment

2023-07-03 20:05 UTC, dmitr2ish commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
It's your local property, you do have not to push it to the general branch

2023-07-03 20:05 UTC, dmitr2ish commented on src/main/resources/application.properties
> +#spring.datasource2.password=pass
pls delete it, also you dont need to create second db

2023-07-03 20:05 UTC, dmitr2ish commented on src/main/resources/sql/schema2.sql
> +--);
pls delete it

2023-07-04 12:14 UTC, rassl95 commented on src/main/java/com/github/hey_world_team/currency_converter/repository/CurrencyRepositoryImpl.java
> +            return null;
IDEA has fixed it like this

2023-07-08 19:06 UTC, dmitr2ish requested changes
Well done, you need to fix a little bit of the code style issues and update your idea code style of the project. Also, you need to be more careful with adding dependencies and check all changes that you want to push. And for future PRs, let's create different PR for different tasks.

2023-07-15 12:35 UTC, dmitr2ish approved these changes

2023-07-15 12:35 UTC, merged